import { DEFAULT_STAR_MAX } from './constants';
import { Faction, type BirdId, type UnitDefinition, type UnitId } from './types';

export const BIRD_IDS: BirdId[] = [
  'red',
  'chuck',
  'terence',
  'silver',
  'bomb',
  'matilda',
  'hal',
  'stella',
  'blues',
  'bubbles',
  'melody',
];

export const UNIT_CATALOG: Record<UnitId, UnitDefinition> = {
  red: {
    id: 'red',
    displayName: 'Red',
    spriteKey: 'red',
    faction: Faction.Player,
    role: 'melee',
    maxHp: 12,
    attack: 5,
    defense: 2,
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    starPower: 'Battle Cry',
    passive: '+1 defense to adjacent allies.',
  },
  chuck: {
    id: 'chuck',
    displayName: 'Chuck',
    spriteKey: 'chuck',
    faction: Faction.Player,
    role: 'melee',
    maxHp: 9,
    attack: 4,
    defense: 1,
    move: 5,
    rangeMin: 1,
    rangeMax: 1,
    starPower: 'Overdrive',
    passive: 'Ignores terrain movement costs.',
  },
  terence: {
    id: 'terence',
    displayName: 'Terence',
    spriteKey: 'terence',
    faction: Faction.Player,
    role: 'melee',
    maxHp: 18,
    attack: 6,
    defense: 4,
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    sizeW: 2,
    sizeH: 2,
    starPower: 'Bulldozer',
    passive: 'Occupies 2x2 tiles and resists knockback.',
  },
  silver: {
    id: 'silver',
    displayName: 'Silver',
    spriteKey: 'silver',
    faction: Faction.Player,
    role: 'melee',
    maxHp: 10,
    attack: 5,
    defense: 1,
    move: 4,
    rangeMin: 1,
    rangeMax: 1,
    starPower: 'Seismic Loop',
    passive: 'Deals bonus damage to entrenched enemies.',
  },
  bomb: {
    id: 'bomb',
    displayName: 'Bomb',
    spriteKey: 'bomb',
    faction: Faction.Player,
    role: 'indirect',
    maxHp: 11,
    attack: 6,
    defense: 1,
    move: 2,
    rangeMin: 2,
    rangeMax: 3,
    starPower: 'Delayed Nuke',
    passive: 'Cannot move and attack on the same turn. Attacks splash lightly.',
  },
  matilda: {
    id: 'matilda',
    displayName: 'Matilda',
    spriteKey: 'matilda',
    faction: Faction.Player,
    role: 'specialist',
    maxHp: 10,
    attack: 5,
    defense: 1,
    move: 3,
    rangeMin: 2,
    rangeMax: 3,
    starPower: 'Drop & Retreat',
    passive: 'Ignores ground hazards.',
  },
  hal: {
    id: 'hal',
    displayName: 'Hal',
    spriteKey: 'hal',
    faction: Faction.Player,
    role: 'indirect',
    maxHp: 10,
    attack: 4,
    defense: 1,
    move: 3,
    rangeMin: 2,
    rangeMax: 4,
    starPower: 'Backline Snatch',
    passive: 'Can move through enemy-occupied tiles.',
  },
  stella: {
    id: 'stella',
    displayName: 'Stella',
    spriteKey: 'stella',
    faction: Faction.Player,
    role: 'indirect',
    maxHp: 9,
    attack: 4,
    defense: 1,
    move: 3,
    rangeMin: 2,
    rangeMax: 3,
    starPower: 'Anti-Gravity Bubble',
    passive: 'Damaging enemies reduces their move next turn.',
  },
  blues: {
    id: 'blues',
    displayName: 'The Blues',
    spriteKey: 'blues',
    faction: Faction.Player,
    role: 'indirect',
    maxHp: 8,
    attack: 3,
    defense: 0,
    move: 4,
    rangeMin: 2,
    rangeMax: 3,
    starPower: 'Scatter Strike',
    passive: '+15% damage against enemies with zero defense.',
  },
  bubbles: {
    id: 'bubbles',
    displayName: 'Bubbles',
    spriteKey: 'bubbles',
    faction: Faction.Player,
    role: 'melee',
    maxHp: 13,
    attack: 4,
    defense: 2,
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    starPower: 'Sudden Expansion',
    passive: '30% evasion versus indirect attacks.',
  },
  melody: {
    id: 'melody',
    displayName: 'Melody',
    spriteKey: 'melody',
    faction: Faction.Player,
    role: 'indirect',
    maxHp: 10,
    attack: 5,
    defense: 1,
    move: 3,
    rangeMin: 2,
    rangeMax: 3,
    starPower: 'Debris Barrage',
    passive: 'Destroyed structures restore Star Meter.',
  },
  pig_grunt: {
    id: 'pig_grunt',
    displayName: 'Pig Grunt',
    spriteKey: 'pig-grunt',
    faction: Faction.Pig,
    role: 'melee',
    maxHp: 8,
    attack: 3,
    defense: 1,
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    starPower: 'None',
    passive: 'Basic melee soldier.',
  },
  pig_archer: {
    id: 'pig_archer',
    displayName: 'Slinger Pig',
    spriteKey: 'pig-archer',
    faction: Faction.Pig,
    role: 'indirect',
    maxHp: 7,
    attack: 3,
    defense: 0,
    move: 2,
    rangeMin: 2,
    rangeMax: 3,
    starPower: 'None',
    passive: 'Indirect attacker.',
  },
  pig_bruiser: {
    id: 'pig_bruiser',
    displayName: 'Bruiser Pig',
    spriteKey: 'pig-bruiser',
    faction: Faction.Pig,
    role: 'melee',
    maxHp: 13,
    attack: 5,
    defense: 3,
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    starPower: 'None',
    passive: 'Slow armored blocker.',
  },
  pig_thief: {
    id: 'pig_thief',
    displayName: 'Thief Pig',
    spriteKey: 'pig-thief',
    faction: Faction.Pig,
    role: 'melee',
    maxHp: 6,
    attack: 2,
    defense: 0,
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    starPower: 'None',
    passive: 'Prioritizes Golden Eggs.',
  },
  pig_boss: {
    id: 'pig_boss',
    displayName: 'Architect Pig',
    spriteKey: 'pig-boss',
    faction: Faction.Pig,
    role: 'indirect',
    maxHp: 22,
    attack: 5,
    defense: 3,
    move: 0,
    rangeMin: 2,
    rangeMax: 5,
    starPower: 'Rule Corruption',
    passive: 'Corrupts the grid rules.',
  },
};

export const STAR_MAX_BY_UNIT: Partial<Record<UnitId, number>> = {
  red: DEFAULT_STAR_MAX,
  chuck: DEFAULT_STAR_MAX,
  terence: 12,
  silver: DEFAULT_STAR_MAX,
  bomb: 12,
  matilda: DEFAULT_STAR_MAX,
  hal: DEFAULT_STAR_MAX,
  stella: DEFAULT_STAR_MAX,
  blues: 8,
  bubbles: DEFAULT_STAR_MAX,
  melody: DEFAULT_STAR_MAX,
};

export const SPRITE_KEYS = Array.from(
  new Set([
    ...Object.values(UNIT_CATALOG).map((unit) => unit.spriteKey),
    'golden-egg',
    'barricade',
    'projectile',
  ]),
);
